appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"kolchak-the-night-stalker-complete-series-1972","",["Kolchak The Night Stalker S00E01 - The Night Stalker.mp4","Kolchak The Night Stalker S00E02 - The Night Strangler.mp4","Kolchak The Night Stalker S01E01 - The Ripper.mp4","Kolchak The Night Stalker S01E02 - The Zombie.mp4","Kolchak The Night Stalker S01E03 - They Have Been They Are They Will Be.mp4","Kolchak The Night Stalker S01E04 - The Vampire.mp4","Kolchak The Night Stalker S01E05 - The Werewolf.mp4","Kolchak The Night Stalker S01E06 - Firefall.mp4","Kolchak The Night Stalker S01E07 - The Devils Platform.mp4","Kolchak The Night Stalker S01E08 - Bad Medicine.mp4","Kolchak The Night Stalker S01E09 - The Spanish Moss Murders.mp4","Kolchak The Night Stalker S01E10 - The Energy Eater.mp4","Kolchak The Night Stalker S01E11 - Horror In The Heights.mp4","Kolchak The Night Stalker S01E12 - Mr RING.mp4","Kolchak The Night Stalker S01E13 - Primal Scream.mp4","Kolchak The Night Stalker S01E14 - The Trevi Collection.mp4","Kolchak The Night Stalker S01E15 - Chopper.mp4","Kolchak The Night Stalker S01E16 - Demon In Lace.mp4","Kolchak The Night Stalker S01E17 - Legacy of Terror.mp4","Kolchak The Night Stalker S01E18 - The Knightly Murders.mp4","Kolchak The Night Stalker S01E19 - The Youth Killer.mp4","Kolchak The Night Stalker S01E20 - The Sentry.mp4"]);
appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"nightmare_castle","",["M4V10002.MP4"]);
appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"one-million-years-bc-1966_202010","",["One Million Years BC (1966).mp4"]);
appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"planet_outlaws_ipod","",["planet_outlaws.mp4"]);
appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"teenagers_from_outerspace","",["Teenagers_from_Outer_Space.mp4"]);
appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"tormented","",["tormented.mp4"]);
appendArchiveFiles(REFINED_SHOCK_DRIVE_IN,"white_zombie","",["white_zombie.mp4"]);
appendArchiveFiles(REFINED_HOLIDAY,"1969-frosty-the-snowman-christmas-movies-for-kids-animated-cartoons-for-children","Holiday",["1952 The Ford Television Theatre ''Heart Of Gold'' w George Reeves (Classic TV Christmas 5 Star).mp4","1969 Frosty the Snowman (Christmas Movies for Kids - animated Cartoons for Children).mp4","1982 Ziggy-s Gift (1982 Christmas Special).mp4","1985 The Glo Friends Save Christmas (1985 Cool Stuff).mp4","1987 Santa Bear-s High-Flying Adventure (Jeff Dalby).mp4","2011 (STEVE AND MAGGIE) Holiday Songs and Stories for Kids - MORE from Steve and Maggie Best Christmas.mp4"]);
appendArchiveFiles(REFINED_HOLIDAY,"AmazingStories","Holiday",["AmazingStories111-Santa85.mp4","AmazingStories209-Thanksgiving.mp4"]);
appendArchiveFiles(REFINED_HOLIDAY,"Dragnet1951","Holiday",["Dragnet/Season 2/Dragnet (1951) - S02E07 - The Big .22 Rifle for Christmas.mp4","Dragnet/Season 4/Dragnet (1951) - S04E12 - The Big New Year.mp4"]);
appendArchiveFiles(REFINED_HOLIDAY,"OTRR_Dragnet_Singles","Holiday",["Dragnet_49-12-22_030_22_Rifle_for_Christmas.mp3","Dragnet_50-12-21_080_22_Rifle_for_Christmas.mp3","Dragnet_51-03-08_091_The_Big_New_Years.mp3","Dragnet_51-12-20_132_22_Rifle_for_Christmas.mp3"]);
appendArchiveFiles(REFINED_HOLIDAY,"OTRR_Richard_Diamond_Private_Detective_Singles","Holiday",["Richard Diamond 49-12-24 (035) A Christmas Carol.mp3","Richard Diamond 51-12-21 (114) Christmas Show.mp3"]);
appendArchiveFiles(REFINED_HOLIDAY,"OTRR_Suspense_Singles","Holiday",["Suspense 431223 071 Back for Christmas (128-44) 28057 29m12s.mp3"]);
appendArchiveFiles(REFINED_HOLIDAY,"OTRR_Whistler_Singles","Holiday",["Whistler_44-12-25_ep135_Christmas_Bonus.mp3","Whistler_48-12-26_ep342_Delayed_Christmas_Present.mp3"]);
appendArchiveFiles(REFINED_HOLIDAY,"OTRR_YoursTrulyJohnnyDollar_Singles","Holiday",["YTJD 1949-12-24 030 The Department Store Swindle Matter (How I Played Santa Claus And Almost Got Left Holding The Bag).mp3"]);
appendArchiveFiles(REFINED_HOLIDAY,"TalesOfTheTexasRangers","Holiday",["Texas_Rangers_1950_12_24_24_Christmas_Present.mp3","Texas_Rangers_1951_12_23_58_Christmas_Payoff.mp3"]);
appendArchiveFiles(REFINED_HOLIDAY,"Winston_Churchill","Holiday",["1941-12-24_BBC_Winston_Churchill_The_White_House_Christmas_Tree.mp3","1944-11-23_BBC_Winston_Churchill_Americas_Thanksgiving_Day.mp3"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1221_Economy_Twins_Cigar_Ernie_60-339_Ford_TV_Spot_1960","Vintage Auto Ad",["1221_Economy_Twins_Cigar_Ernie_60-339_Ford_TV_Spot_1960_00_05_51_00_3mb.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1954CommercialForMercury","Vintage Auto Ad",["1954CommercialForMercury.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1955Chev1955","Vintage Auto Ad",["1955Chev1955_edit.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1955CommercialForChryslerforwardLook","Vintage Auto Ad",["ForwardLookCommercial1955.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1955CommercialForPlymouthBelvedereTurbine","Vintage Auto Ad",["PlymouthTurbine1955.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1956CommercialFor1957ChryslerRangead1","Vintage Auto Ad",["1956for1957chrysler.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1956CommercialFor1957ChryslerRangead2","Vintage Auto Ad",["1956for1957chryslerAd2.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1956CommercialForChevroletStationWagons","Vintage Auto Ad",["1956chevroletstationwagons.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1956CommercialForChryslerTorsion-aireRide","Vintage Auto Ad",["Torsion-AireRideDeSoto-1956Adfor1957.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1957CommercialsForTheEdsel","Vintage Auto Ad",["Edsel1957Ad1.mp4","Edsel1957Ad2.mp4","Edsel1957Ad3.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1958ChevroletTrucks","Vintage Auto Ad",["1958ChevroletTrucks.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1958ILoveLucyFordCommercials","Vintage Auto Ad",["1958 I Love Lucy Ford Commercials.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1958for1958OldsmobileAd4","Vintage Auto Ad",["1958for1958OldsmobileAd4.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1958for1959oldsmobile","Vintage Auto Ad",["1958for1959oldsmobile.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1959CommercialFor1960Chevrolet","Vintage Auto Ad",["chevrolet1960.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1959CommercialFor1960ChevroletBelAir","Vintage Auto Ad",["1960chevroletBelair.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1960CommercialForChevroletTrucks","Vintage Auto Ad",["1960ChevroletTrucks.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1960CommercialForOkUsedCars","Vintage Auto Ad",["OKusedCars1960.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1960For1961ChevroletChristmasShopping","Vintage Auto Ad",["1960 for 1961 Chevrolet - Christmas shopping.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1967DogdeDartTvCommercialPamAustinClips","Vintage Auto Ad",["Dodgedart.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1977ChevroletConcours","Vintage Auto Ad",["1977 Chevrolet Concours.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"1977ChevroletWithJerryOrbach","Vintage Auto Ad",["1977 Chevrolet with Jerry Orbach.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"58OldsmobileCommercials","Vintage Auto Ad",["58Oldsmobile-aired1957.mp4","58OldsmobileAired1957Ad2.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"Classic1967CommercialForChevyIiNova","Vintage Auto Ad",["Chevy2Nova_512kb.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"ClassicCommercialForFordFalconusaCirca1966","Vintage Auto Ad",["Falcon_512kb.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"CommercialFor1955Dodge","Vintage Auto Ad",["1955Dodge.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"CommercialFor1956DodgeTexan","Vintage Auto Ad",["dodgetexan.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"PontiacGto1966CarCommercialTvAd","Vintage Auto Ad",["GTOad.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"SeatbeltPSAs","Vintage Auto Ad",["SeatbeltPSAs.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"ToughAC1973Campaign","Vintage Auto Ad",["ToughAC1973Campaign.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"Wonderfu1960","Vintage Auto Ad",["Wonderfu1960_edit.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"chevrolet1956for1957Chevy","Vintage Auto Ad",["chevrolet1956for1957Chevy.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"trabant601","Vintage Auto Ad",["trabant601_512kb.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"wartburg_1000_1966","Vintage Auto Ad",["wartburg_1000_1966_512kb.mp4"]);
appendArchiveFiles(REFINED_VINTAGE_AUTO_ADS,"watashi-wa-beretto","Vintage Auto Ad",["Watashi-wa beretto.mp4"]);
