// ============================================================
// SCHOOLHOUSE ROCK - 73 VERIFIED ORIGINAL MP4 FILES
// Source: Archive.org item schoolhouse-rock-30th
// Verified by Imperial Physics Mega Archive Harvester V2
// HTTP ranged GET PASS; video/mp4 originals
// ============================================================

const SCHOOLHOUSE_ROCK = [
    {n: "Schoolhouse Rock - 01 Three Is A Magic Number", u: "https://archive.org/download/schoolhouse-rock-30th/01%20Three%20Is%20A%20Magic%20Number.mp4"},
    {n: "Schoolhouse Rock - 02 My Hero Zero", u: "https://archive.org/download/schoolhouse-rock-30th/02%20My%20Hero%20Zero.mp4"},
    {n: "Schoolhouse Rock - 03 Elementary My Dear", u: "https://archive.org/download/schoolhouse-rock-30th/03%20Elementary%20My%20Dear.mp4"},
    {n: "Schoolhouse Rock - 04 The Four Legged Zoo", u: "https://archive.org/download/schoolhouse-rock-30th/04%20The%20Four%20Legged%20Zoo.mp4"},
    {n: "Schoolhouse Rock - 05 Ready Or Not Here I Come", u: "https://archive.org/download/schoolhouse-rock-30th/05%20Ready%20Or%20Not%20Here%20I%20Come.mp4"},
    {n: "Schoolhouse Rock - 06 I Got Six", u: "https://archive.org/download/schoolhouse-rock-30th/06%20I%20Got%20Six.mp4"},
    {n: "Schoolhouse Rock - 07 Lucky Seven Sampson", u: "https://archive.org/download/schoolhouse-rock-30th/07%20Lucky%20Seven%20Sampson.mp4"},
    {n: "Schoolhouse Rock - 08 Figure Eight", u: "https://archive.org/download/schoolhouse-rock-30th/08%20Figure%20Eight.mp4"},
    {n: "Schoolhouse Rock - 09 Naughty Number Nine", u: "https://archive.org/download/schoolhouse-rock-30th/09%20Naughty%20Number%20Nine.mp4"},
    {n: "Schoolhouse Rock - 10 The Good Eleven", u: "https://archive.org/download/schoolhouse-rock-30th/10%20The%20Good%20Eleven.mp4"},
    {n: "Schoolhouse Rock - 11 Little Twelvetoes", u: "https://archive.org/download/schoolhouse-rock-30th/11%20Little%20Twelvetoes.mp4"},
    {n: "Schoolhouse Rock - 12 A Noun Is A Person Place Or Thing", u: "https://archive.org/download/schoolhouse-rock-30th/12%20A%20Noun%20Is%20A%20Person%20Place%20Or%20Thing.mp4"},
    {n: "Schoolhouse Rock - 13 Verb Thats Whats Happening", u: "https://archive.org/download/schoolhouse-rock-30th/13%20Verb%20Thats%20Whats%20Happening.mp4"},
    {n: "Schoolhouse Rock - 14 Conjunction Junction", u: "https://archive.org/download/schoolhouse-rock-30th/14%20Conjunction%20Junction.mp4"},
    {n: "Schoolhouse Rock - 15 Interjections", u: "https://archive.org/download/schoolhouse-rock-30th/15%20Interjections.mp4"},
    {n: "Schoolhouse Rock - 16 Unpack Your Adjectives", u: "https://archive.org/download/schoolhouse-rock-30th/16%20Unpack%20Your%20Adjectives.mp4"},
    {n: "Schoolhouse Rock - 17 Lolly Lolly Lolly Get Your Adverbs Here", u: "https://archive.org/download/schoolhouse-rock-30th/17%20Lolly%20Lolly%20Lolly%20Get%20Your%20Adverbs%20Here.mp4"},
    {n: "Schoolhouse Rock - 18 Rufus Xavier Sasparilla", u: "https://archive.org/download/schoolhouse-rock-30th/18%20Rufus%20Xavier%20Sasparilla.mp4"},
    {n: "Schoolhouse Rock - 19 Busy Prepositions", u: "https://archive.org/download/schoolhouse-rock-30th/19%20Busy%20Prepositions.mp4"},
    {n: "Schoolhouse Rock - 20 The Tale Of Mr Morton", u: "https://archive.org/download/schoolhouse-rock-30th/20%20The%20Tale%20Of%20Mr%20Morton.mp4"},
    {n: "Schoolhouse Rock - 21 No More Kings", u: "https://archive.org/download/schoolhouse-rock-30th/21%20No%20More%20Kings.mp4"},
    {n: "Schoolhouse Rock - 22 The Shot Heard Round the World", u: "https://archive.org/download/schoolhouse-rock-30th/22%20The%20Shot%20Heard%20Round%20the%20World.mp4"},
    {n: "Schoolhouse Rock - 23 The Preamble", u: "https://archive.org/download/schoolhouse-rock-30th/23%20The%20Preamble.mp4"},
    {n: "Schoolhouse Rock - 24 Sufferin Till Suffrage", u: "https://archive.org/download/schoolhouse-rock-30th/24%20Sufferin%20Till%20Suffrage.mp4"},
    {n: "Schoolhouse Rock - 25 Im Just A Bill", u: "https://archive.org/download/schoolhouse-rock-30th/25%20Im%20Just%20A%20Bill.mp4"},
    {n: "Schoolhouse Rock - 26 The Great American Melting Pot", u: "https://archive.org/download/schoolhouse-rock-30th/26%20The%20Great%20American%20Melting%20Pot.mp4"},
    {n: "Schoolhouse Rock - 27 Elbow Room", u: "https://archive.org/download/schoolhouse-rock-30th/27%20Elbow%20Room.mp4"},
    {n: "Schoolhouse Rock - 28 Fireworks", u: "https://archive.org/download/schoolhouse-rock-30th/28%20Fireworks.mp4"},
    {n: "Schoolhouse Rock - 29 Mother Necessity", u: "https://archive.org/download/schoolhouse-rock-30th/29%20Mother%20Necessity.mp4"},
    {n: "Schoolhouse Rock - 30 Three Ring Government", u: "https://archive.org/download/schoolhouse-rock-30th/30%20Three%20Ring%20Government.mp4"},
    {n: "Schoolhouse Rock - 31 Im Gonna Send Your Vote To College In Surround", u: "https://archive.org/download/schoolhouse-rock-30th/31%20Im%20Gonna%20Send%20Your%20Vote%20To%20College%20In%20Surround.mp4"},
    {n: "Schoolhouse Rock - 32 You Earned Your Diploma and Presidential Minute", u: "https://archive.org/download/schoolhouse-rock-30th/32%20You%20Earned%20Your%20Diploma%20and%20Presidential%20Minute.mp4"},
    {n: "Schoolhouse Rock - 33 A Victim Of Gravity", u: "https://archive.org/download/schoolhouse-rock-30th/33%20A%20Victim%20Of%20Gravity.mp4"},
    {n: "Schoolhouse Rock - 34 Interplanet Janet", u: "https://archive.org/download/schoolhouse-rock-30th/34%20Interplanet%20Janet.mp4"},
    {n: "Schoolhouse Rock - 35 The Body Machine", u: "https://archive.org/download/schoolhouse-rock-30th/35%20The%20Body%20Machine.mp4"},
    {n: "Schoolhouse Rock - 36 Do The Circulation", u: "https://archive.org/download/schoolhouse-rock-30th/36%20Do%20The%20Circulation.mp4"},
    {n: "Schoolhouse Rock - 37 The Energy Blues", u: "https://archive.org/download/schoolhouse-rock-30th/37%20The%20Energy%20Blues.mp4"},
    {n: "Schoolhouse Rock - 38 Them Not So Dry Bones", u: "https://archive.org/download/schoolhouse-rock-30th/38%20Them%20Not%20So%20Dry%20Bones.mp4"},
    {n: "Schoolhouse Rock - 39 Electricity Electricity", u: "https://archive.org/download/schoolhouse-rock-30th/39%20Electricity%20Electricity.mp4"},
    {n: "Schoolhouse Rock - 40 Telegraph Line", u: "https://archive.org/download/schoolhouse-rock-30th/40%20Telegraph%20Line.mp4"},
    {n: "Schoolhouse Rock - 41 The Weather Show", u: "https://archive.org/download/schoolhouse-rock-30th/41%20The%20Weather%20Show.mp4"},
    {n: "Schoolhouse Rock - 42 Scooter Computer Introduction", u: "https://archive.org/download/schoolhouse-rock-30th/42%20Scooter%20Computer%20Introduction.mp4"},
    {n: "Schoolhouse Rock - 43 Scooter Computer Hardware", u: "https://archive.org/download/schoolhouse-rock-30th/43%20Scooter%20Computer%20Hardware.mp4"},
    {n: "Schoolhouse Rock - 44 Scooter Computer Software", u: "https://archive.org/download/schoolhouse-rock-30th/44%20Scooter%20Computer%20Software.mp4"},
    {n: "Schoolhouse Rock - 45 Scooter Computer Number Cruncher", u: "https://archive.org/download/schoolhouse-rock-30th/45%20Scooter%20Computer%20Number%20Cruncher.mp4"},
    {n: "Schoolhouse Rock - 46 Dollars And Sense", u: "https://archive.org/download/schoolhouse-rock-30th/46%20Dollars%20And%20Sense.mp4"},
    {n: "Schoolhouse Rock - 47 Tax Man Max", u: "https://archive.org/download/schoolhouse-rock-30th/47%20Tax%20Man%20Max.mp4"},
    {n: "Schoolhouse Rock - 48 Where The Money Goes", u: "https://archive.org/download/schoolhouse-rock-30th/48%20Where%20The%20Money%20Goes.mp4"},
    {n: "Schoolhouse Rock - 49 Seven Dollars Fifty Cents Once A Week", u: "https://archive.org/download/schoolhouse-rock-30th/49%20Seven%20Dollars%20Fifty%20Cents%20Once%20A%20Week.mp4"},
    {n: "Schoolhouse Rock - 50 Tyrannosaurus Debt", u: "https://archive.org/download/schoolhouse-rock-30th/50%20Tyrannosaurus%20Debt.mp4"},
    {n: "Schoolhouse Rock - 51 This For That", u: "https://archive.org/download/schoolhouse-rock-30th/51%20This%20For%20That.mp4"},
    {n: "Schoolhouse Rock - 52 Walkin On The Wall Street", u: "https://archive.org/download/schoolhouse-rock-30th/52%20Walkin%20On%20The%20Wall%20Street.mp4"},
    {n: "Schoolhouse Rock - 53 The Checks In The Mail", u: "https://archive.org/download/schoolhouse-rock-30th/53%20The%20Checks%20In%20The%20Mail.mp4"},
    {n: "Schoolhouse Rock - 54 Report from the North Pole", u: "https://archive.org/download/schoolhouse-rock-30th/54%20Report%20from%20the%20North%20Pole.mp4"},
    {n: "Schoolhouse Rock - 55 The Little Things We Do", u: "https://archive.org/download/schoolhouse-rock-30th/55%20The%20Little%20Things%20We%20Do.mp4"},
    {n: "Schoolhouse Rock - 56 The Trash Can Band", u: "https://archive.org/download/schoolhouse-rock-30th/56%20The%20Trash%20Can%20Band.mp4"},
    {n: "Schoolhouse Rock - 57 You Oughta Be Savin Water", u: "https://archive.org/download/schoolhouse-rock-30th/57%20You%20Oughta%20Be%20Savin%20Water.mp4"},
    {n: "Schoolhouse Rock - 58 The Rainforest", u: "https://archive.org/download/schoolhouse-rock-30th/58%20The%20Rainforest.mp4"},
    {n: "Schoolhouse Rock - 59 Save the Ocean", u: "https://archive.org/download/schoolhouse-rock-30th/59%20Save%20the%20Ocean.mp4"},
    {n: "Schoolhouse Rock - 60 Fat Cat Blue - The Clean Rivers Song", u: "https://archive.org/download/schoolhouse-rock-30th/60%20Fat%20Cat%20Blue%20-%20The%20Clean%20Rivers%20Song.mp4"},
    {n: "Schoolhouse Rock - 61 A Tiny Urban Zoo", u: "https://archive.org/download/schoolhouse-rock-30th/61%20A%20Tiny%20Urban%20Zoo.mp4"},
    {n: "Schoolhouse Rock - 62 Solar Power to the People", u: "https://archive.org/download/schoolhouse-rock-30th/62%20Solar%20Power%20to%20the%20People.mp4"},
    {n: "Schoolhouse Rock - 63 Windy and the Windmills", u: "https://archive.org/download/schoolhouse-rock-30th/63%20Windy%20and%20the%20Windmills.mp4"},
    {n: "Schoolhouse Rock - 64 Don't Be a Carbon Sasquatch", u: "https://archive.org/download/schoolhouse-rock-30th/64%20Don%27t%20Be%20a%20Carbon%20Sasquatch.mp4"},
    {n: "Schoolhouse Rock - 65 The Three Rs", u: "https://archive.org/download/schoolhouse-rock-30th/65%20The%20Three%20Rs.mp4"},
    {n: "Schoolhouse Rock - 66 Music Video - Conjunction Junction - Better Than Ezra", u: "https://archive.org/download/schoolhouse-rock-30th/66%20Music%20Video%20-%20Conjunction%20Junction%20-%20Better%20Than%20Ezra.mp4"},
    {n: "Schoolhouse Rock - 67 Music Video - Electricity Electricity - Goodness", u: "https://archive.org/download/schoolhouse-rock-30th/67%20Music%20Video%20-%20Electricity%20Electricity%20-%20Goodness.mp4"},
    {n: "Schoolhouse Rock - 68 Music Video - Im Just a Bill - Deluxe Folk Implosion", u: "https://archive.org/download/schoolhouse-rock-30th/68%20Music%20Video%20-%20Im%20Just%20a%20Bill%20-%20Deluxe%20Folk%20Implosion.mp4"},
    {n: "Schoolhouse Rock - 69 Music Video - My Hero Zero - Lemonheads", u: "https://archive.org/download/schoolhouse-rock-30th/69%20Music%20Video%20-%20My%20Hero%20Zero%20-%20Lemonheads.mp4"},
    {n: "Schoolhouse Rock - 70 The Making Of Im Gonna Send Your Vote To College", u: "https://archive.org/download/schoolhouse-rock-30th/70%20The%20Making%20Of%20Im%20Gonna%20Send%20Your%20Vote%20To%20College.mp4"},
    {n: "Schoolhouse Rock - 71 Directors Commentaries", u: "https://archive.org/download/schoolhouse-rock-30th/71%20Directors%20Commentaries.mp4"},
    {n: "Schoolhouse Rock - 72 Emmy Awards Featurette", u: "https://archive.org/download/schoolhouse-rock-30th/72%20Emmy%20Awards%20Featurette.mp4"},
    {n: "Schoolhouse Rock - 73 Nike Commercial Three is a Magic Number", u: "https://archive.org/download/schoolhouse-rock-30th/73%20Nike%20Commercial%20Three%20is%20A%20Magic%20Number.mp4"},
];
